#
# Author: Jonah Kubath
# Class: CS4430 A4 Northwind
#
SRC = ./CS4430_A4_JonahKubath/src
BIN = ./CS4430_A4_JonahKubath/bin



build: 
	javac -d $(BIN) -cp $(SRC) CS4430_A4_JonahKubath/src/a4_JonahKubath/*.java

use:
	java -cp $(BIN)/mysql-connector-java-5.1.46-bin.jar:$(BIN) a4_JonahKubath/Main


